# Generated by Django 5.1.4 on 2024-12-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_post_hashtag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
